import { Article } from './models/Article';

export const articles = [
    new Article(
        'Lorem ipsum 29/01/2020',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar tincidunt nulla, et pharetra nulla volutpat ac.  Pellentesque vel tincidunt nunc. Cras faucibus pharetra consequat.  Aliquam consectetur lacus sagittis, efficitur ligula eu, dignissim elit.  Sed posuere felis id quam aliquam rutrum.  Donec vehicula est vel nulla bibendum tincidunt. Suspendisse potenti. Ut tempor sed tortor a pulvinar. Duis in volutpat leo. Vivamus iaculis facilisis massa, id maximus ligula fermentum sit amet. Proin et ex efficitur, aliquam tellus a, varius turpis. Curabitur egestas sem eget augue malesuada, quis elementum dolor efficitur. Fusce lacinia leo sed sapien mattis volutpat. Cras quis varius erat. Nullam dignissim lacus sit amet purus ornare condimentum. Sed vulputate, est molestie finibus varius, purus felis convallis mauris, maximus semper ante purus in dolor. Ut sit amet tincidunt augue. Vestibulum consectetur ex id eros pharetra,  vitae interdum ligula scelerisque. Nunc et egestas est.',
        'https://hatrabbits.com/wp-content/uploads/2017/01/random.jpg'
    ),
    new Article(
        'Lorem ipsum 22/01/2020',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar tincidunt nulla, et pharetra nulla volutpat ac.  Pellentesque vel tincidunt nunc. Cras faucibus pharetra consequat.  Aliquam consectetur lacus sagittis, efficitur ligula eu, dignissim elit.  Sed posuere felis id quam aliquam rutrum.  Donec vehicula est vel nulla bibendum tincidunt. Suspendisse potenti. Ut tempor sed tortor a pulvinar. Duis in volutpat leo. Vivamus iaculis facilisis massa, id maximus ligula fermentum sit amet. Proin et ex efficitur, aliquam tellus a, varius turpis. Curabitur egestas sem eget augue malesuada, quis elementum dolor efficitur. Fusce lacinia leo sed sapien mattis volutpat. Cras quis varius erat. Nullam dignissim lacus sit amet purus ornare condimentum. Sed vulputate, est molestie finibus varius, purus felis convallis mauris, maximus semper ante purus in dolor. Ut sit amet tincidunt augue. Vestibulum consectetur ex id eros pharetra,  vitae interdum ligula scelerisque. Nunc et egestas est.',
        'https://image.jeuxvideo.com/medias-sm/156052/1560524284-7295-jaquette-avant.png'
    ),
    new Article(
        'Lorem ipsum 21/01/2020',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar tincidunt nulla, et pharetra nulla volutpat ac.  Pellentesque vel tincidunt nunc. Cras faucibus pharetra consequat.  Aliquam consectetur lacus sagittis, efficitur ligula eu, dignissim elit.  Sed posuere felis id quam aliquam rutrum.  Donec vehicula est vel nulla bibendum tincidunt. Suspendisse potenti. Ut tempor sed tortor a pulvinar. Duis in volutpat leo. Vivamus iaculis facilisis massa, id maximus ligula fermentum sit amet. Proin et ex efficitur, aliquam tellus a, varius turpis. Curabitur egestas sem eget augue malesuada, quis elementum dolor efficitur. Fusce lacinia leo sed sapien mattis volutpat. Cras quis varius erat. Nullam dignissim lacus sit amet purus ornare condimentum. Sed vulputate, est molestie finibus varius, purus felis convallis mauris, maximus semper ante purus in dolor. Ut sit amet tincidunt augue. Vestibulum consectetur ex id eros pharetra,  vitae interdum ligula scelerisque. Nunc et egestas est.',
        'https://new-game-plus.fr/wp-content/uploads/2020/06/Lost-in-Random-1.jpg'
    ),
    new Article(
        'Lorem ipsum 09/01/2020',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar tincidunt nulla, et pharetra nulla volutpat ac.  Pellentesque vel tincidunt nunc. Cras faucibus pharetra consequat.  Aliquam consectetur lacus sagittis, efficitur ligula eu, dignissim elit.  Sed posuere felis id quam aliquam rutrum.  Donec vehicula est vel nulla bibendum tincidunt. Suspendisse potenti. Ut tempor sed tortor a pulvinar. Duis in volutpat leo. Vivamus iaculis facilisis massa, id maximus ligula fermentum sit amet. Proin et ex efficitur, aliquam tellus a, varius turpis. Curabitur egestas sem eget augue malesuada, quis elementum dolor efficitur. Fusce lacinia leo sed sapien mattis volutpat. Cras quis varius erat. Nullam dignissim lacus sit amet purus ornare condimentum. Sed vulputate, est molestie finibus varius, purus felis convallis mauris, maximus semper ante purus in dolor. Ut sit amet tincidunt augue. Vestibulum consectetur ex id eros pharetra,  vitae interdum ligula scelerisque. Nunc et egestas est.',
        'https://image.jeuxvideo.com/medias-sm/156052/1560524284-7295-jaquette-avant.png'
    ),
    new Article(
        'Lorem ipsum 08/01/2020',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar tincidunt nulla, et pharetra nulla volutpat ac.  Pellentesque vel tincidunt nunc. Cras faucibus pharetra consequat.  Aliquam consectetur lacus sagittis, efficitur ligula eu, dignissim elit.  Sed posuere felis id quam aliquam rutrum.  Donec vehicula est vel nulla bibendum tincidunt. Suspendisse potenti. Ut tempor sed tortor a pulvinar. Duis in volutpat leo. Vivamus iaculis facilisis massa, id maximus ligula fermentum sit amet. Proin et ex efficitur, aliquam tellus a, varius turpis. Curabitur egestas sem eget augue malesuada, quis elementum dolor efficitur. Fusce lacinia leo sed sapien mattis volutpat. Cras quis varius erat. Nullam dignissim lacus sit amet purus ornare condimentum. Sed vulputate, est molestie finibus varius, purus felis convallis mauris, maximus semper ante purus in dolor. Ut sit amet tincidunt augue. Vestibulum consectetur ex id eros pharetra,  vitae interdum ligula scelerisque. Nunc et egestas est.',
        'https://hatrabbits.com/wp-content/uploads/2017/01/random.jpg'
    ),
    new Article(
        'Lorem ipsum 07/01/2020',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar tincidunt nulla, et pharetra nulla volutpat ac.  Pellentesque vel tincidunt nunc. Cras faucibus pharetra consequat.  Aliquam consectetur lacus sagittis, efficitur ligula eu, dignissim elit.  Sed posuere felis id quam aliquam rutrum.  Donec vehicula est vel nulla bibendum tincidunt. Suspendisse potenti. Ut tempor sed tortor a pulvinar. Duis in volutpat leo. Vivamus iaculis facilisis massa, id maximus ligula fermentum sit amet. Proin et ex efficitur, aliquam tellus a, varius turpis. Curabitur egestas sem eget augue malesuada, quis elementum dolor efficitur. Fusce lacinia leo sed sapien mattis volutpat. Cras quis varius erat. Nullam dignissim lacus sit amet purus ornare condimentum. Sed vulputate, est molestie finibus varius, purus felis convallis mauris, maximus semper ante purus in dolor. Ut sit amet tincidunt augue. Vestibulum consectetur ex id eros pharetra,  vitae interdum ligula scelerisque. Nunc et egestas est.',
        'https://new-game-plus.fr/wp-content/uploads/2020/06/Lost-in-Random-1.jpg'
    ),
    new Article(
        'Lorem ipsum 06/01/2020',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar tincidunt nulla, et pharetra nulla volutpat ac.  Pellentesque vel tincidunt nunc. Cras faucibus pharetra consequat.  Aliquam consectetur lacus sagittis, efficitur ligula eu, dignissim elit.  Sed posuere felis id quam aliquam rutrum.  Donec vehicula est vel nulla bibendum tincidunt. Suspendisse potenti. Ut tempor sed tortor a pulvinar. Duis in volutpat leo. Vivamus iaculis facilisis massa, id maximus ligula fermentum sit amet. Proin et ex efficitur, aliquam tellus a, varius turpis. Curabitur egestas sem eget augue malesuada, quis elementum dolor efficitur. Fusce lacinia leo sed sapien mattis volutpat. Cras quis varius erat. Nullam dignissim lacus sit amet purus ornare condimentum. Sed vulputate, est molestie finibus varius, purus felis convallis mauris, maximus semper ante purus in dolor. Ut sit amet tincidunt augue. Vestibulum consectetur ex id eros pharetra,  vitae interdum ligula scelerisque. Nunc et egestas est.',
        'https://hatrabbits.com/wp-content/uploads/2017/01/random.jpg'
    ),
    new Article(
        'Lorem ipsum 02/01/2020',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar tincidunt nulla, et pharetra nulla volutpat ac.  Pellentesque vel tincidunt nunc. Cras faucibus pharetra consequat.  Aliquam consectetur lacus sagittis, efficitur ligula eu, dignissim elit.  Sed posuere felis id quam aliquam rutrum.  Donec vehicula est vel nulla bibendum tincidunt. Suspendisse potenti. Ut tempor sed tortor a pulvinar. Duis in volutpat leo. Vivamus iaculis facilisis massa, id maximus ligula fermentum sit amet. Proin et ex efficitur, aliquam tellus a, varius turpis. Curabitur egestas sem eget augue malesuada, quis elementum dolor efficitur. Fusce lacinia leo sed sapien mattis volutpat. Cras quis varius erat. Nullam dignissim lacus sit amet purus ornare condimentum. Sed vulputate, est molestie finibus varius, purus felis convallis mauris, maximus semper ante purus in dolor. Ut sit amet tincidunt augue. Vestibulum consectetur ex id eros pharetra,  vitae interdum ligula scelerisque. Nunc et egestas est.',
        'https://image.jeuxvideo.com/medias-sm/156052/1560524284-7295-jaquette-avant.png'
    )
];